// 通用函数

/**
 * each
 * extend
 * extend2Lev
 * coverExtend
 * isArray
 * isFunction
 * isArguments
 * toArray
 * values
 * indexof
 * filter
 * inherit
 * trim
 * isObject
 * isEmptyObject
 * isUndefined
 * isString
 * isDate
 * isBoolean
 * isNumber
 * isElement
 * isJSONString
 * safeJSONParse
 * decodeURIComponent
 * encodeDates
 * mediaQueriesSupported
 * getScreenOrientation
 * now
 * throttle
 * hashCode
 * formatDate
 * searchObjDate
 * searchZZAppStyle
 * formatJsonString
 * formatString
 * searchObjString
 * searchConfigData
 * unique
 * strip_sa_properties
 * strip_empty_properties
 * utf8Encode
 * base64Encode
 * UUID
 * getQueryParam
 * urlParse
 * addEvent
 * addHashEvent
 * addSinglePageEvent
 * cookie
 * getEleInfo
 * localStorage
 * sessionStorage
 * isSupportCors
 * xhr
 * ajax
 * loadScript
 * getHostname
 * getQueryParamsFromUrl
 * getURLSearchParams
 * URL
 * getCurrentDomain
 * getCookieTopLevelDomain
 * isReferralTraffic
 * ry
 * strToUnicode
 * getReferrer
 * getKeywordFromReferrer
 * getReferSearchEngine
 * getSourceFromReferrer
 * info
 * autoExeQueue
 * trackLink
 */
